spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/english?useSSL=true&amp;verifyServerCertificate=false&amp;serverTimezone=GMT％2B8
    url: jdbc:mysql://localhost:3306/english
    username: root
    password: 137805


server:
  port: 8080